# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 222ae8dc989a5cf99f259b951cb7b288cf020bf9e40f93bb4d4705db4a09845bf60ae89b02876615e9d6445afef6c5b863ed894c4b24b2f0b08abae5b07943ff

test:
  secret_key_base: c630018d7e804ae4a72f34623b2be8a45d536d0c818a47984b179674920668f98f1397492bbac59219ad87a4da51e1c69f901d5f52b4d3a8e2b03921d93063d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
